services:
  - type: web
    name: fastapi-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.api.main:app --reload
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
